Imported csv file into pandas

In [6]:
import pandas as pd
import io

Seperated by '\\' to create table format

In [7]:
shop = pd.read_csv(('customer_shopping_behavior.csv'), sep='\t')

In [8]:
shop.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly

In [9]:
shop.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

Null values in 'Reveiew Rating'

In [12]:
shop.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

Clean null values by category

In [11]:
shop['Review Rating'] = shop.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

Converting all column's name into lowercase & removing spaces by underscore to avoid errors

In [13]:
shop.columns = shop.columns.str.lower()
shop.columns = shop.columns.str.replace(' ','_')
shop = shop.rename(columns = {'purchase_amount_(usd)' : 'purchase_amount'})
shop.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

Create new column "age_group"

In [14]:
labels = ['Young Adult', 'Adult', 'Senior', 'Middle Age']
shop['age_group'] = pd.qcut(shop['age'], q=4, labels = labels)

In [15]:
shop[['age', 'age_group']].head(10)

   age    age_group
0   55       Senior
1   19  Young Adult
2   50       Senior
3   21  Young Adult
4   45       Senior
5   46       Senior
6   63   Middle Age
7   27  Young Adult
8   26  Young Adult
9   57       Senior

Created dictionary for frequency of mapping

In [16]:
frequency_mapping = {
    'Fortnightly' : 14,
    'Weekly' : 7,
    'Monthly' : 30,
    'Quarterly' : 90,
    'Bi-Weekly' : 14,
    'Annually' : 365,
    'Every 3 Months' : 90
}

shop['frequency'] = shop['frequency_of_purchases'].map(frequency_mapping)
shop[['frequency','frequency_of_purchases']].head(40)

    frequency frequency_of_purchases
0          14            Fortnightly
1          14            Fortnightly
2           7                 Weekly
3           7                 Weekly
4         365               Annually
5           7                 Weekly
6          90              Quarterly
7           7                 Weekly
8         365               Annually
9          90              Quarterly
10         14              Bi-Weekly
11         14            Fortnightly
12         14            Fortnightly
13          7                 Weekly
14          7                 Weekly
15         30                Monthly
16         14              Bi-Weekly
17         90              Quarterly
18          7                 Weekly
19         14              Bi-Weekly
20         90         Every 3 Months
21         90              Quarterly
22        365               Annually
23          7                 Weekly
24          7                 Weekly
25        365               Annually
26        365               Annually
27         90         Every 3 Months
28         90         Every 3 Months
29          7                 Weekly
30         30                Monthly
31         30                Monthly
32        365               Annually
33         90              Quarterly
34         90              Quarterly
35         14              Bi-Weekly
36         14            Fortnightly
37          7                 Weekly
38         90         Every 3 Months
39         30                Monthly

Shaping the column

In [17]:
shop[['discount_applied','promo_code_used']].head(10)        # checking both column values--
(shop['discount_applied'] == shop['promo_code_used']).all()  # checking if both are same--
shop = shop.drop('promo_code_used', axis=1)                  # droping column permanently--
shop.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'frequency'],
      dtype='object')

In [18]:
shop.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'frequency'],
      dtype='object')

In [19]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\asset\appdata\roaming\python\python313\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [28]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

#Step 1: Connect to PostgresQL


username = "postgres"

password = "Priyanka@16"
encoded_password = quote_plus(password)
print(encoded_password)

host = "localhost"
port = "5432"
database = "customer_shopping_behavior"

engine = create_engine(f"postgresql+psycopg2://postgres:Priyanka%4016@localhost:5432/customer_shopping_behavior")

Priyanka%4016

In [29]:
# Step 2: Load DataFrame into PostgreSOL

table_name = "custo"
database = "customer_shopping_behavior"
shop.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'custo' in database 'customer_shopping_behavior'.